/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalinteligencia.views;

/**
 *
 * @author dsantillanes
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCon1 = new javax.swing.JButton();
        btnCon2 = new javax.swing.JButton();
        btnCon3 = new javax.swing.JButton();
        btnCon4 = new javax.swing.JButton();
        btnCon5 = new javax.swing.JButton();
        btnCon6 = new javax.swing.JButton();
        btnCon7 = new javax.swing.JButton();
        btnCon8 = new javax.swing.JButton();
        btnCon9 = new javax.swing.JButton();
        btnCon10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCon1.setText("Consulta 1");
        btnCon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon1ActionPerformed(evt);
            }
        });

        btnCon2.setText("Consulta 2");
        btnCon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon2ActionPerformed(evt);
            }
        });

        btnCon3.setText("Consulta 3");
        btnCon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon3ActionPerformed(evt);
            }
        });

        btnCon4.setText("Consulta 4");
        btnCon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon4ActionPerformed(evt);
            }
        });

        btnCon5.setText("Consulta 5");
        btnCon5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon5ActionPerformed(evt);
            }
        });

        btnCon6.setText("Consulta 6");
        btnCon6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon6ActionPerformed(evt);
            }
        });

        btnCon7.setText("Consulta 7");
        btnCon7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon7ActionPerformed(evt);
            }
        });

        btnCon8.setText("Consulta 8");
        btnCon8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon8ActionPerformed(evt);
            }
        });

        btnCon9.setText("Consulta 9");
        btnCon9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon9ActionPerformed(evt);
            }
        });

        btnCon10.setText("Consulta 10");
        btnCon10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCon10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnCon4)
                        .addGap(50, 50, 50)
                        .addComponent(btnCon5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCon6)
                                .addGap(33, 33, 33)
                                .addComponent(btnCon7)
                                .addGap(39, 39, 39)
                                .addComponent(btnCon8)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCon1)
                                .addGap(34, 34, 34)
                                .addComponent(btnCon2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCon3)))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnCon9)
                .addGap(45, 45, 45)
                .addComponent(btnCon10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCon1)
                    .addComponent(btnCon2)
                    .addComponent(btnCon3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCon4)
                    .addComponent(btnCon5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCon6)
                    .addComponent(btnCon7)
                    .addComponent(btnCon8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCon9)
                    .addComponent(btnCon10))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon1ActionPerformed
        Consulta1 consulta1 = new Consulta1();
        consulta1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon1ActionPerformed

    private void btnCon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon2ActionPerformed
        Consulta2 consulta2 = new Consulta2();
        consulta2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon2ActionPerformed

    private void btnCon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon3ActionPerformed
        Consulta3 consulta3 = new Consulta3();
        consulta3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon3ActionPerformed

    private void btnCon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon4ActionPerformed
        Consulta4 consulta4 = new Consulta4();
        consulta4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon4ActionPerformed

    private void btnCon5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon5ActionPerformed
        Consulta5 consulta5 = new Consulta5();
        consulta5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon5ActionPerformed

    private void btnCon6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon6ActionPerformed
        Consulta6 consulta6 = new Consulta6();
        consulta6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon6ActionPerformed

    private void btnCon7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon7ActionPerformed
        Consulta7 consulta7 = new Consulta7();
        consulta7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon7ActionPerformed

    private void btnCon8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon8ActionPerformed
        Consulta8 consulta8 = new Consulta8();
        consulta8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon8ActionPerformed

    private void btnCon9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon9ActionPerformed
        Consulta9 consulta9 = new Consulta9();
        consulta9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon9ActionPerformed

    private void btnCon10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCon10ActionPerformed
        Consulta10 consulta10 = new Consulta10();
        consulta10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCon10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCon1;
    private javax.swing.JButton btnCon10;
    private javax.swing.JButton btnCon2;
    private javax.swing.JButton btnCon3;
    private javax.swing.JButton btnCon4;
    private javax.swing.JButton btnCon5;
    private javax.swing.JButton btnCon6;
    private javax.swing.JButton btnCon7;
    private javax.swing.JButton btnCon8;
    private javax.swing.JButton btnCon9;
    // End of variables declaration//GEN-END:variables
}
